##로그인
POST http://localhost:8080/api/tokens
Content-Type: application/json

{"username":"user","password":"1234"}

###회원 가입 테스트
POST http://localhost:8080/api/members/new
Content-Type: application/json

{"username":"user", "password":"1234", "name":"이범준", "phoneNum":"2323", "email": "dd@dd"}

###회원 티켓 조회 테스트
GET http://localhost:8080/api/members/tickets
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlXyI6WyJST0xFX1VTRVIiXSwiaXNzIjoibGVlYmVvbWp1biIsImV4cCI6MTYxMDk4NjI5MywidXNlcm5hbWUiOiJ1c2VyIn0.3nXoFCuCYIEl6imoaAWyurB-2cjTUBvz6_YsYLoNteM

###회원 티켓 취소 테스트
DELETE http://localhost:8080/api/members/tickets
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlXyI6WyJST0xFX1VTRVIiXSwiaXNzIjoibGVlYmVvbWp1biIsImV4cCI6MTYxMDk4NjI5MywidXNlcm5hbWUiOiJ1c2VyIn0.3nXoFCuCYIEl6imoaAWyurB-2cjTUBvz6_YsYLoNteM